name: Shopping Scanner
version: "1.0.1"
slug: shopping_scanner
description: Barcode scanner for Home Assistant shopping lists with offline product database
url: https://github.com/Siweaver1971/ha-shopping-scanner
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
ingress: true
ingress_port: 9999
panel_icon: mdi:barcode-scan
panel_title: Shopping Scanner
ports:
  9999/tcp: null
options:
  ssl: false
schema:
  ssl: bool
image: ghcr.io/siweaver1971/{arch}-addon-shopping-scanner
